apiVersion: v1
kind: Pod
metadata:
  # Unique key of the Job instance
  name: datadownload-job
spec:
  #  template:
  #  metadata:
  #    name: datadownload-job
  #  spec:
      containers:
      - name: datadownload-job
        image: datadownload
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /downloaData/amfidata
          name: amfidata
          readOnly: false
        - mountPath: /downloaData/jsondata
          name: jsondata
          readOnly: false
      # Do not restart containers after they exit
      restartPolicy: Never
      volumes:
      - name: amfidata
        hostPath:
          path: /downloaData/amfidata
      - name: jsondata
        hostPath:
          path: /downloaData/jsondata

